### ISSUE TITLE
vypsat pořadí hráče v http://is.ufobal.cz/statistiky

### ISSUE THREAD

**Issue by jojkos** [thran/ufobal-web#14]
vypsat vedle hráče jeho pořadí i v případě, že ho vyhledám (abych věděl kolikátej sem)

**Comment by thran** [comment]
pořadí kde?

**Comment by jojkos** [comment]
ve statistikách nalevo před jménem asi

**Comment by thran** [comment]
pořadí vůči čemu? tomu jak je to zrovna v té tabulce (tj na zákládě aktuálního filtrování?)

**Comment by jojkos** [comment]
jo, nic lepšího mě nenapadá

**Comment by thran** [comment]
nepřijde mě to moc užitečný, ale OK
