### ISSUE TITLE
doak nemůže ukládat svoje týmy

### ISSUE THREAD

**Issue by jojkos** [thran/ufobal-web#15]
POST http://is.ufobal.cz/angular/reverse/?djng_url_name=api%3Aadd_attendance 403 (FORBIDDEN)

**Comment by thran** [comment]
Někdo to taky psal, ale mě to jede, tak nevím

**Comment by thran** [comment]
už vím, chybí csfr token - klasika, ne kterou jako vyvojář nikdy nepříjdeš...

**Comment by jojkos** [comment]
pro nas je to nak vyply potreba ho mit? sem se zkousel i odlogovat a stejne mi to jelo

**Comment by thran** [comment]
no protože to cookinu už máš načtenou a tu odhlášením nesmažeš
