### ISSUE TITLE
Doplnit týmy na turnaje

### ISSUE THREAD

**Issue by thran** [thran/ufobal-web#16]
- [x] hala 2014 je špatně
- [ ] hala 2013
- [x] Nížkov 2010
- [x] Nížkov 2008
- [x] starší Nížkovy (doplněny první místa)

**Comment by jojkos** [comment]
https://fbcdn-sphotos-e-a.akamaihd.net/hphotos-ak-ash2/v/t1.0-9/fr/cp0/e15/q65/10247264_10202796760232293_616212718_n.jpg?efg=eyJpIjoidCJ9&oh=7ff8306171380e50a99a24fe957002eb&oe=573BB004&__gda__=1463648014_703f6b8ee5779dc46ca651937c2ea81f
fotka existuje

**Comment by thran** [comment]
Good job

**Comment by jojkos** [comment]
přidal jsem výsledky po 2002 a jeden ročník ve 2000 z toho co tam bylo dostupný

**Comment by thran** [comment]
Close due to inactivity.
