### ISSUE TITLE
přidat k userum v adminovi jejich uzivatele a zjistit proč (hned první logy ukázaly), že se někdo nezvládl spárovat

### ISSUE THREAD

**Issue by jojkos** [thran/ufobal-web#29]
http://is.ufobal.cz/admin/ufobalapp/log/
http://is.ufobal.cz/admin/ufobalapp/player/1492/?_changelist_filters=q%3Dv%25C3%25ADt

**Comment by jojkos** [comment]
podle 
http://is.ufobal.cz/admin/auth/user/
toho že skoro nikdo není spárovanej, tak si možná všichni myslí že stačí navštívit ten link a už pak neklikají na spárovat (i když tam je napsaný "Následně potvrďte propojení")

**Comment by thran** [comment]
Tak text nikdo nečte, ale myslím, že když tam je input field a velký tlačítko, tak je zřejmý že to máš ještě zmáčknout. Já bych se tím moc netrápil.

**Comment by thran** [comment]
Tak je to asi moje blbost. Jak jsem to omezoval, tak jsem omezil spárování účtu na jen spárované uživatele...
Opraveno v a2ab18438de5fae6adb75b9448fe53b03fa3f9ad
Lidem, kterých se to asi dotklo napíšu mail.

**Comment by jojkos** [comment]
Ještě můžu kdyžtak odhadnutelny lidi ručně sparovat
Dne 12. 3. 2016 10:45 AM napsal uživatel "Thran" <notifications@github.com>:

**Comment by thran** [comment]
Jak chceš. Já jim každopádně, teď napíšu.
