### ISSUE TITLE
Implementovat pořadí na turnaji

### ISSUE THREAD

**Issue by thran** [thran/ufobal-web#6]
- [x] asi bude stačit int u TeamOnTournament
- [x] nějaký POST view, kterýmu přijdou v datech seznam týmůNaTurnaji (asi jako id) a to pořadí s k nim uloží
- [ ] a pak by to chtělo v adminovy nejlépe nějaký  dobrý drag&drop (https://angular-ui.github.io/ui-sortable/)  ale to bude asi spíš na mě, leda že bys chtěl

**Comment by jojkos** [comment]
chvíli jsem zkoušel ten drag&drop, ale nikam jsem se moc nedostal... ještě to ale chci zkusit (y). Musím si udělat vlastní controller v app.js a pak view co mi vrátí json týmů a pak už to teprve můžu haluzit v šabloně, kde jsem pochopil, asi musím použit {% verbatim %}?

**Comment by thran** [comment]
{% verbatim %} musíš použít aby ses "dostal" do angularové syntaxe a nebyla chápana jako djangovská.
Jinak více méně ano

**Comment by thran** [comment]
dump

**Comment by jojkos** [comment]
asi dobry
