### ISSUE TITLE
Goalies' statistics

### ISSUE THREAD

**Issue by jakub-h** [thran/ufobal-web#61]
Brankarske statistiky (https://is.ufobal.cz/brankari) se chovaji zvlastne. Pri filtrovani podle odehranych zapasu mizi a objevuji se i brankari, ktere by to nemelo vyfiltrovat. Mozna to je zpusobene jen tim, ze to neni automaticky serazene podle uspesnosti zakroku a ti brankari zmizi jen na druhou stranku. Prislo by mi logictejsi, aby byli defaultne serazeni podle uspesnosti zakroku.

**Comment by thran** [comment]
Přidal jsem defaultní řazení do statistik střelců a golmanů
