### ISSUE TITLE
Use first player set as goalie for a match as team default goalie, if the team doesn't have a default one

### ISSUE THREAD

**Issue by jojkos** [thran/ufobal-web#70]

**Comment by thran** [comment]
Proč první? Nepovede to jen k tomu, že se zapomene to zadat?

**Comment by jojkos** [comment]
myslel jsem prvniho zadanyho brankare, aby kdyz zalozis hru a nastavis brankare tymu co nema ulozenyho defaultniho, tak se automaticky jako defaultni propsal

**Comment by thran** [comment]
Aha, už to chápu. Špatně jsem naparsoval. Tu větu

**Comment by thran** [comment]
Sem to udělal, ale vlastně si nejsem jistý jestlo to dává smysl. Pro týmy které střídají víc lidí tak je to feature, že se to každý západ musí explicitně říct a nezapomene se na to.
