### ISSUE TITLE
Problem s presmerovanim

### ISSUE THREAD

**Issue by mat3sj** [thran/ufobal-web#72]
Behem prihlasovani na tenhle turnaj melo hodne lidi problem se prihlasit. Kdyz sli na aktualni turnaj, tak je presmerovalo na /turnaj/124/Ivancice misto na /turnaj/124/ a tlacitko zpet nedela pry vubec nic. Nevim, cim to je, nepodarilo se mi to zduplikovat - resp se mi to povedlo zduplikovat, kdyz jsem nebyl prihlasenej, ale vsichni dotazovani pry prihlaseni byli.

**Comment by thran** [comment]
Byl to opravdu bug, který se neprojevoval pro adminy. Ta stránka na, kterou se nedalo dostat byla zakázána mimo den turnaje. Takže dnes by to mělo fungovat tak jako tak, ale už je to i opravený 8e2a12a6b78ac0c4e312e8ee52ee2556c293d957
