### ISSUE TITLE
Pridat filtry ve statistikach

### ISSUE THREAD

**Issue by mat3sj** [thran/ufobal-web#74]
Momentalne filtry ve statistikach nefunguji - trenink je tam vzdycky, liga vubec. Navrhuji pridat filtr pro kazdou kategorii (Hala, Brno, Nizkov, Dalsi turnaj, trenink, liga). Na jare pobezi v brne liga a v praze mozna budeme zapisovat treninky, tak at to dava nejakej smysl po letosni sezone :)

**Comment by thran** [comment]
S těmi tréningy to byla chyba (překlep). Tréningy a ligy tam nejsou nikdy. Přišlo mi, že jsou to věci natolik odlišné, že je nikdy nedává smysl dávat dokupy s nějakýma dalšíma eventama.

Ale ty ligy tam můžeme přidat.

**Comment by mat3sj** [comment]
Ty ligy by byly asi fajn. A jeste nevim, jestli jde liga editovat (kdyz
nejses admin) bez toho, aby si pokazde menil datum turnaje. Bud umoznit
vicedenni turnaj, nebo proste pro turnaj s kategorii liga umoznit editaci
do konce turnaje.

pá 1. 4. 2022 v 16:11 odesílatel Thran ***@***.***> napsal:

**Comment by thran** [comment]
Ligy jsem tam přidal. 
Ligy a tréningy by měli být editovatelný nezávisle na datu. Až to bude uzavřený tak by se v adminu měla zaškrtnout `Uzavřená editace`
